name: 'Linter'

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'tests/**'
jobs:
  lint:
    name: 'Lint code'
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.8"
    - name: Install requirements
      run: | 
        pip install -r src/requirements.txt
        pip install pylint==3.3.3
    - name: Lint code
      run: | 
        pylint --fail-under=9.3 src/
