name: 'Release on PyPi (Development)'
on:
  push:
    branches:
    - develop
    paths:
    - src/**
  workflow_dispatch:

jobs:
   publish-dev:
    name: 'Publish on PyPi'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src/
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install requirements
      run: | 
        pip install wheel==0.42.0
        pip install twine==4.0.2
        pip install setuptools==65.5.0
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Check package
      run: twine check dist/*
    - name: Publish
      run: twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u ${{ secrets.PYPI_TEST_USER }} -p '${{ secrets.PYPI_TEST_PASSWORD }}'